# Generated by Django 4.2 on 2023-04-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('comp_name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=100)),
                ('bee_no', models.CharField(max_length=100)),
                ('bbbee_level', models.IntegerField(default=1)),
            ],
        ),
    ]
